In [1]:
import pandas as pd

In [2]:
time = [10, 20, 30, 40]
print(time)
ser = pd.Series(time)
print(ser)

[10, 20, 30, 40]
0    10
1    20
2    30
3    40
dtype: int64


In [3]:
input = [[10, "a", True], [20, "b", False], [30, "c", False], [40, "d", True]]
print(input)

[[10, 'a', True], [20, 'b', False], [30, 'c', False], [40, 'd', True]]


In [4]:
pd.DataFrame(input)

0  1      2
0  10  a   True
1  20  b  False
2  30  c  False
3  40  d   True

In [5]:
df = pd.DataFrame(input)

In [6]:
import numpy as np
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
np.arange(100).shape

(100,)

In [8]:
np.arange(100).reshape((25, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [9]:
np.arange(100).reshape((25, 4)).shape

(25, 4)

In [10]:
np.arange(100).reshape((25, 4)).shape[0]

25

In [11]:
np.arange(100).reshape((25, 4)).shape[1]

4

In [12]:
pd.DataFrame(np.arange(100).reshape((25, 4)))

0   1   2   3
0    0   1   2   3
1    4   5   6   7
2    8   9  10  11
3   12  13  14  15
4   16  17  18  19
5   20  21  22  23
6   24  25  26  27
7   28  29  30  31
8   32  33  34  35
9   36  37  38  39
10  40  41  42  43
11  44  45  46  47
12  48  49  50  51
13  52  53  54  55
14  56  57  58  59
15  60  61  62  63
16  64  65  66  67
17  68  69  70  71
18  72  73  74  75
19  76  77  78  79
20  80  81  82  83
21  84  85  86  87
22  88  89  90  91
23  92  93  94  95
24  96  97  98  99

In [13]:
df = pd.DataFrame(np.arange(100).reshape((25, 4)))

In [14]:
df.head()

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [15]:
df.head(3)

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [16]:
df.tail()

0   1   2   3
20  80  81  82  83
21  84  85  86  87
22  88  89  90  91
23  92  93  94  95
24  96  97  98  99

In [17]:
np.arange(6).reshape((3, 2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
pd.DataFrame(np.arange(6).reshape((3, 2)))

0  1
0  0  1
1  2  3
2  4  5

In [19]:
# df = pd.DataFrame(np.arange(6).reshape((3, 2)))
# df.index = ["01", "02", "03"]
# df.columns = ["A", "B"]
pd.DataFrame(np.arange(6).reshape((3, 2)), index = ["01", "02", "03"], columns= ["A", "B"])

A  B
01  0  1
02  2  3
03  4  5

In [20]:
df = pd.DataFrame(np.arange(6).reshape((3, 2)), index = ["01", "02", "03"], columns= ["A", "B"])

In [21]:
df["A"]

01    0
02    2
03    4
Name: A, dtype: int64

In [22]:
df["B"]

01    1
02    3
03    5
Name: B, dtype: int64

In [23]:
df.iloc[:, 0]

01    0
02    2
03    4
Name: A, dtype: int64

In [24]:
select = ["A", "B"]
df[select]

A  B
01  0  1
02  2  3
03  4  5

In [25]:
df[:2]

A  B
01  0  1
02  2  3

In [26]:
df.iloc[:2, :]

A  B
01  0  1
02  2  3

In [27]:
df.loc[:, "A"]

01    0
02    2
03    4
Name: A, dtype: int64

In [28]:
df.loc[:, select]

A  B
01  0  1
02  2  3
03  4  5

In [29]:
df.loc[["01", "03"], select]

A  B
01  0  1
03  4  5

In [30]:
pd.read_csv("ES=F.csv", encoding = "utf-8")

Date    Close  Adj Close
0    2019/11/24  3118.25    3118.25
1    2019/11/25  3132.75    3132.75
2    2019/11/26  3143.75    3143.75
3    2019/11/27  3153.75    3153.75
4    2019/11/29      NaN        NaN
..          ...      ...        ...
119   2020/4/17  2869.00    2869.00
120   2020/4/19  2847.50    2847.50
121   2020/4/20  2814.00    2814.00
122   2020/4/21  2736.50    2736.50
123   2020/4/22  2775.00    2775.00

[124 rows x 3 columns]

In [31]:
# df = pd.read_csv("ES=F.csv", encoding = "utf-8")
df = pd.read_excel("ES=F.xlsx", encoding = "utf-8")

In [32]:
df.head()

Date    Close  Adj Close
0 2019-11-24  3118.25    3118.25
1 2019-11-25  3132.75    3132.75
2 2019-11-26  3143.75    3143.75
3 2019-11-27  3153.75    3153.75
4 2019-11-29      NaN        NaN

In [33]:
df.to_excel("testA.xlsx")

In [34]:
df["Close"]>3000

0       True
1       True
2       True
3       True
4      False
       ...  
119    False
120    False
121    False
122    False
123    False
Name: Close, Length: 124, dtype: bool

In [35]:
df[df["Close"]>3000]

Date        Close    Adj Close
0  2019-11-24  3118.250000  3118.250000
1  2019-11-25  3132.750000  3132.750000
2  2019-11-26  3143.750000  3143.750000
3  2019-11-27  3153.750000  3153.750000
5  2019-12-01  3146.750000  3146.750000
..        ...          ...          ...
77 2020-02-27  3110.250000  3110.250000
81 2020-03-03  3065.100098  3065.100098
83 2020-03-05  3114.699951  3114.699951
84 2020-03-06  3015.500000  3015.500000
85 2020-03-08  3015.500000  3015.500000

[80 rows x 3 columns]

In [36]:
df[df["Close"]>3000].shape

(80, 3)

In [37]:
df.query("Close > 3000 and Close < 3100")

Date        Close    Adj Close
7  2019-12-03  3091.000000  3091.000000
81 2020-03-03  3065.100098  3065.100098
84 2020-03-06  3015.500000  3015.500000
85 2020-03-08  3015.500000  3015.500000

In [38]:
df.dtypes

Date         datetime64[ns]
Close               float64
Adj Close           float64
dtype: object

In [39]:
df.iloc[4, 1]

nan

In [40]:
type(df.iloc[4, 1])

numpy.float64

In [41]:
df.iloc[4, 1] == "nan"

False

In [42]:
np.isnan(df.iloc[4, 1])

True

In [43]:
~np.isnan(df.iloc[4, 1])

False

In [44]:
np.isnan(df)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [45]:
df[~np.isnan(df.iloc[4, 1])

SyntaxError: unexpected EOF while parsing (<ipython-input-45-ebfa74d7d3f4>, line 1)

In [46]:
# Q1: 輸出 0000-1000 的 list
# Q2: 輸出 沒有nan的excel

In [47]:
### Q1 sol01

In [48]:
print("\n".join(['{0:04}'.format(num) for num in range(0, 1000)]))

0000
0001
0002
0003
0004
0005
0006
0007
0008
0009
0010
0011
0012
0013
0014
0015
0016
0017
0018
0019
0020
0021
0022
0023
0024
0025
0026
0027
0028
0029
0030
0031
0032
0033
0034
0035
0036
0037
0038
0039
0040
0041
0042
0043
0044
0045
0046
0047
0048
0049
0050
0051
0052
0053
0054
0055
0056
0057
0058
0059
0060
0061
0062
0063
0064
0065
0066
0067
0068
0069
0070
0071
0072
0073
0074
0075
0076
0077
0078
0079
0080
0081
0082
0083
0084
0085
0086
0087
0088
0089
0090
0091
0092
0093
0094
0095
0096
0097
0098
0099
0100
0101
0102
0103
0104
0105
0106
0107
0108
0109
0110
0111
0112
0113
0114
0115
0116
0117
0118
0119
0120
0121
0122
0123
0124
0125
0126
0127
0128
0129
0130
0131
0132
0133
0134
0135
0136
0137
0138
0139
0140
0141
0142
0143
0144
0145
0146
0147
0148
0149
0150
0151
0152
0153
0154
0155
0156
0157
0158
0159
0160
0161
0162
0163
0164
0165
0166
0167
0168
0169
0170
0171
0172
0173
0174
0175
0176
0177
0178
0179
0180
0181
0182
0183
0184
0185
0186
0187
0188
0189
0190
0191
0192
0193
0194
0195
0196
0197
0198
0199


In [49]:
### Q1 sol02

In [50]:
print ("\n".join([str(num).rjust(4, '0') for num in range(0, 1000)]))

0000
0001
0002
0003
0004
0005
0006
0007
0008
0009
0010
0011
0012
0013
0014
0015
0016
0017
0018
0019
0020
0021
0022
0023
0024
0025
0026
0027
0028
0029
0030
0031
0032
0033
0034
0035
0036
0037
0038
0039
0040
0041
0042
0043
0044
0045
0046
0047
0048
0049
0050
0051
0052
0053
0054
0055
0056
0057
0058
0059
0060
0061
0062
0063
0064
0065
0066
0067
0068
0069
0070
0071
0072
0073
0074
0075
0076
0077
0078
0079
0080
0081
0082
0083
0084
0085
0086
0087
0088
0089
0090
0091
0092
0093
0094
0095
0096
0097
0098
0099
0100
0101
0102
0103
0104
0105
0106
0107
0108
0109
0110
0111
0112
0113
0114
0115
0116
0117
0118
0119
0120
0121
0122
0123
0124
0125
0126
0127
0128
0129
0130
0131
0132
0133
0134
0135
0136
0137
0138
0139
0140
0141
0142
0143
0144
0145
0146
0147
0148
0149
0150
0151
0152
0153
0154
0155
0156
0157
0158
0159
0160
0161
0162
0163
0164
0165
0166
0167
0168
0169
0170
0171
0172
0173
0174
0175
0176
0177
0178
0179
0180
0181
0182
0183
0184
0185
0186
0187
0188
0189
0190
0191
0192
0193
0194
0195
0196
0197
0198
0199


In [51]:
### Q1 sol03

In [52]:
for i in range(1000):
    print('{:d}'.format(i).zfill(4))

0000
0001
0002
0003
0004
0005
0006
0007
0008
0009
0010
0011
0012
0013
0014
0015
0016
0017
0018
0019
0020
0021
0022
0023
0024
0025
0026
0027
0028
0029
0030
0031
0032
0033
0034
0035
0036
0037
0038
0039
0040
0041
0042
0043
0044
0045
0046
0047
0048
0049
0050
0051
0052
0053
0054
0055
0056
0057
0058
0059
0060
0061
0062
0063
0064
0065
0066
0067
0068
0069
0070
0071
0072
0073
0074
0075
0076
0077
0078
0079
0080
0081
0082
0083
0084
0085
0086
0087
0088
0089
0090
0091
0092
0093
0094
0095
0096
0097
0098
0099
0100
0101
0102
0103
0104
0105
0106
0107
0108
0109
0110
0111
0112
0113
0114
0115
0116
0117
0118
0119
0120
0121
0122
0123
0124
0125
0126
0127
0128
0129
0130
0131
0132
0133
0134
0135
0136
0137
0138
0139
0140
0141
0142
0143
0144
0145
0146
0147
0148
0149
0150
0151
0152
0153
0154
0155
0156
0157
0158
0159
0160
0161
0162
0163
0164
0165
0166
0167
0168
0169
0170
0171
0172
0173
0174
0175
0176
0177
0178
0179
0180
0181
0182
0183
0184
0185
0186
0187
0188
0189
0190
0191
0192
0193
0194
0195
0196
0197
0198
0199


In [53]:
### Q2

In [54]:
pd.read_csv("ES=F.csv", encoding = "utf-8")

Date    Close  Adj Close
0    2019/11/24  3118.25    3118.25
1    2019/11/25  3132.75    3132.75
2    2019/11/26  3143.75    3143.75
3    2019/11/27  3153.75    3153.75
4    2019/11/29      NaN        NaN
..          ...      ...        ...
119   2020/4/17  2869.00    2869.00
120   2020/4/19  2847.50    2847.50
121   2020/4/20  2814.00    2814.00
122   2020/4/21  2736.50    2736.50
123   2020/4/22  2775.00    2775.00

[124 rows x 3 columns]

In [55]:
nan_value = float("NaN")

In [56]:
df.replace("", nan_value, inplace=True)

In [57]:
df.dropna(subset = ["Close", "Adj Close"], inplace=True)
print(df)

          Date    Close  Adj Close
0   2019-11-24  3118.25    3118.25
1   2019-11-25  3132.75    3132.75
2   2019-11-26  3143.75    3143.75
3   2019-11-27  3153.75    3153.75
5   2019-12-01  3146.75    3146.75
..         ...      ...        ...
119 2020-04-17  2869.00    2869.00
120 2020-04-19  2847.50    2847.50
121 2020-04-20  2814.00    2814.00
122 2020-04-21  2736.50    2736.50
123 2020-04-22  2775.00    2775.00

[121 rows x 3 columns]
